#!/bin/bash

echo "=== SenseCAP Indicator D1S Flashing Guide for Fedora 43 KDE ==="
echo ""

echo "Setup Status:"
echo "✓ Fedora Entwicklungstools installiert"
echo "✓ Arduino CLI für RP2040 eingerichtet"
echo "✓ ESP-IDF v5.1 Repository geklont"
echo "✓ Alle Libraries für RP2040 installiert"
echo ""

echo "============================================="
echo "1. RP2040 FLASHEN (zuerst!)"
echo "============================================="
echo ""
echo "Vorgehensweise:"
echo "1. BOOTSEL-Taste auf dem RP2040 (hinten) drücken und halten"
echo "2. USB-Kabel für RP2040 anschließen (BOOTSEL gedrückt halten)"
echo "3. Es erscheint ein USB-Datenträger 'RPI-RP2'"
echo "4. Firmware kompilieren:"
echo "   cd ~/sensecap-firmware/SenseCAP_Indicator_RP2040"
echo "   arduino-cli compile --fqbn rp2040:rp2040:rpipico indicator_rp2040.ino"
echo ""
echo "5. Flashen (Option A - Drag & Drop):"
echo "   Die .uf2 Datei aus build/ auf den RPI-RP2 Drive ziehen"
echo ""
echo "6. Oder (Option B - Arduino CLI):"
echo "   arduino-cli upload --fqbn rp2040:rp2040:rpipico -p /dev/ttyACM0 indicator_rp2040.ino"
echo ""

echo "============================================="
echo "2. ESP32 FLASHEN"
echo "============================================="
echo ""
echo "WICHTIG: ESP-IDF muss noch installiert werden:"
echo "   cd ~/esp-idf"
echo "   ./install.sh"
echo ""
echo "Danach Flashen:"
echo "   source ~/esp-idf/export.sh"
echo "   cd ~/sensecap-firmware/SenseCAP_Indicator_ESP32"
echo "   idf.py set-target esp32s3"
echo "   idf.py build"
echo "   idf.py -p /dev/ttyUSB0 flash monitor"
echo ""
echo "WICHTIG: PSRAM Octal 120M Patch anwenden!"
echo "Siehe: https://wiki.seeedstudio.com/SenseCAP_Indicator_ESP32_Flash/"
echo ""

echo "============================================="
echo "HINWEISE ZUM FLASHING"
echo "============================================="
echo ""
echo "RP2040:"
echo "- RP2040 zuerst flashen (Sensoren-Koprozessor)"
echo "- BOOTSEL-Taste beim Anschließen drücken"
echo "- USB-Gerät ist /dev/ttyACM0"
echo ""
echo "ESP32:"
echo "- ESP32 danach flashen (Main Controller)"
echo "- USB-Gerät ist /dev/ttyUSB0"
echo "- PSRAM Octal 120M Patch ist erforderlich!"
echo ""
echo "USB-Port-Erkennung:"
echo "- dmesg | grep -i tty (nach dem Anschließen)"
echo "- ls -l /dev/ttyUSB* /dev/ttyACM*"
echo ""

echo "============================================="
echo "NACH DEM FLASHEN"
echo "============================================="
echo ""
echo "1. Beide Firmwares sind geflasht"
echo "2. SenseCAP Indicator D1S automatisch booten"
echo "3. Ersteinrichtung über Display durchführen"
echo "4. Sensoren werden automatisch erkannt (falls angeschlossen)"
echo ""
